version: '3.8'

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "grmz"
      POSTGRES_USER: "grmz"
      POSTGRES_PASSWORD: "grmz"
    volumes:      
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
