spring:
  profiles:
    active: local

  application:
    name: groomingzone

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    root: DEBUG
    org:
#      springframework:
#        transaction:
#          interceptor: TRACE         # 트랜잭션 인터셉터의 동작 과정을 상세히 추적 (메서드 진입/종료, 트랜잭션 시작/종료 등)
#        jdbc:
#          datasource:
#            DataSourceTransactionManager: DEBUG  # JDBC 트랜잭션 매니저의 동작을 로깅 (트랜잭션 시작, 커밋, 롤백 등)
#        orm:
#          jpa:
#            JpaTransactionManager: DEBUG  # JPA 트랜잭션 매니저의 동작을 로깅 (트랜잭션 생성, 커밋, 롤백 등)
      hibernate:
        resource:
          transaction: DEBUG         # Hibernate 트랜잭션 리소스 관리 로깅 (커넥션 획득/반환, 세션 관리 등)
        SQL: DEBUG                  # Hibernate가 생성하고 실행하는 모든 SQL문을 출력
        type: TRACE                 # SQL 파라미터 바인딩 값을 출력 (예: binding parameter [1] as [VARCHAR] - [value])

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:classpath:/application-db.yml # spring.config.import ...

  jpa:
    hibernate:
      ddl-auto: none


---
spring:
  config:
    activate:
      on-profile: local
    import: optional:classpath:/application-db.yml # spring.config.import ...

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
